// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSWIDf2qzfungx9jlcyvtKrZGEmMf5zjs',
    appId: '1:523115666456:web:d3bce87c198c432d6c776d',
    messagingSenderId: '523115666456',
    projectId: 'student-class-baf43',
    authDomain: 'student-class-baf43.firebaseapp.com',
    storageBucket: 'student-class-baf43.appspot.com',
    measurementId: 'G-LDLSWGTDF8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjn8MPpR34d8u3zx_K4VTuQh8OAlHj3FU',
    appId: '1:523115666456:android:aa9e37cdf0ab13276c776d',
    messagingSenderId: '523115666456',
    projectId: 'student-class-baf43',
    storageBucket: 'student-class-baf43.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLiAVzQBF9i7BcrYrUMPdRT1x5uW7ra0c',
    appId: '1:523115666456:ios:3a21fe6ca86e4ff56c776d',
    messagingSenderId: '523115666456',
    projectId: 'student-class-baf43',
    storageBucket: 'student-class-baf43.appspot.com',
    androidClientId: '523115666456-t703iccrc087ke6anuctai8bsaksa9ii.apps.googleusercontent.com',
    iosClientId: '523115666456-6c23pplpg0brquvlrd2kosfsbkkj5hcd.apps.googleusercontent.com',
    iosBundleId: 'com.example.digitalSchoolAssessmentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLiAVzQBF9i7BcrYrUMPdRT1x5uW7ra0c',
    appId: '1:523115666456:ios:3a21fe6ca86e4ff56c776d',
    messagingSenderId: '523115666456',
    projectId: 'student-class-baf43',
    storageBucket: 'student-class-baf43.appspot.com',
    androidClientId: '523115666456-t703iccrc087ke6anuctai8bsaksa9ii.apps.googleusercontent.com',
    iosClientId: '523115666456-6c23pplpg0brquvlrd2kosfsbkkj5hcd.apps.googleusercontent.com',
    iosBundleId: 'com.example.digitalSchoolAssessmentApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSWIDf2qzfungx9jlcyvtKrZGEmMf5zjs',
    appId: '1:523115666456:web:746159d83efd13736c776d',
    messagingSenderId: '523115666456',
    projectId: 'student-class-baf43',
    authDomain: 'student-class-baf43.firebaseapp.com',
    storageBucket: 'student-class-baf43.appspot.com',
    measurementId: 'G-BQ3V8ZJETB',
  );

}